services:

  backend:
    depends_on:
      - psql
    ports:
      - ${APP_PORT}:${APP_PORT}

  psql:
    image: postgres:alpine
    ports:
      - "5433:5432"
    volumes:
      - "psql_data:/var/lib/postgresql/data"
    environment:
      POSTGRES_USER: ${PSQL_USER}
      POSTGRES_PASSWORD: ${PSQL_PASS}
      POSTGRES_DB: ${PSQL_DB}

  zookeeper:
    image: docker.io/bitnami/zookeeper:3.8
    ports:
      - "2182:2181"
    volumes:
      - "zookeeper_data:/bitnami"
    environment:
      - ALLOW_ANONYMOUS_LOGIN=yes

  kafka:
    image: docker.io/bitnami/kafka:3.2
    ports:
      - "9093:9092"
    volumes:
      - "kafka_data:/bitnami"
    restart: on-failure
    environment:
      - KAFKA_CFG_ZOOKEEPER_CONNECT=zookeeper:2181
      - ALLOW_PLAINTEXT_LISTENER=yes
    depends_on:
      - zookeeper

volumes:
  psql_data: {}
  zookeeper_data:
    driver: local
  kafka_data:
    driver: local
