"""init1

Revision ID: 523632727f2f
Revises: 61a6c652900a
Create Date: 2024-12-01 02:11:58.642175

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision: str = '523632727f2f'
down_revision: Union[str, None] = '61a6c652900a'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('CargoInsurance',
    sa.Column('cargo_type', sa.String(), nullable=True),
    sa.Column('rate', sa.Double(), nullable=True),
    sa.Column('date', sa.TIMESTAMP(), nullable=True),
    sa.Column('id', sa.UUID(), server_default=sa.text('gen_random_uuid()'), nullable=False),
    sa.Column('updated_at', sa.TIMESTAMP(), server_default=sa.text('now()'), nullable=True),
    sa.Column('created_at', sa.TIMESTAMP(), server_default=sa.text('now()'), nullable=True),
    sa.Column('updated_by', sa.UUID(), nullable=True),
    sa.Column('created_by', sa.UUID(), nullable=True),
    sa.Column('description', sa.String(), nullable=True),
    sa.Column('changelog', postgresql.JSONB(astext_type=sa.Text()), server_default=sa.text("'[]'::json"), nullable=True),
    sa.PrimaryKeyConstraint('id'),
    schema='public',
    comment='CargoInsuranceBase'
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('CargoInsurance', schema='public')
    # ### end Alembic commands ###
